services:
    wk_google_spreadsheet:
        class: Wk\GoogleSpreadsheetBundle\Services\SpreadsheetService
        arguments:
            - "@wk_google_oauth2_for_spreadsheets"

    wk_google_oauth2_for_spreadsheets:
        class: Wk\GoogleSpreadsheetBundle\Services\OAuth2ServiceRequest
        private: true
        arguments:
            - "%wk_google_spreadsheet.credentials_json_file%"
            - "%wk_google_spreadsheet.scope%"
