imports:
    - { resource: parameters.yml }

framework:
    secret: "%kernel.secret%"

wk_google_spreadsheet:
    credentials:
        scope: "https://spreadsheets.google.com/feeds"
        client_email: "%google_spreadsheets.credentials.client_email%"
        private_key: "%google_spreadsheets.credentials.private_key%"