imports:
    - { resource: parameters.yml }

framework:
    secret: "%kernel.secret%"
    test: ~

wk_google_spreadsheet:
    scope: "https://spreadsheets.google.com/feeds"
    credentials_json_file: "%google_spreadsheets_credentials_json_file%"